language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install coveralls

script:
  - python -m unittest tests.test_bitly_minify  tests.test_google_minify
  - coverage run --source=microurl,tests -m unittest tests.test_bitly_minify  tests.test_google_minify

after_success:
  coveralls
